### PR TITLE
Feature/improve deps reference

### PR DESCRIPTION
**Pull request by MangelMaxime**
This PR use webpack to include dependencies:
For example for:

```json
  "basic": {
    "entry": "PixiBasic.fsproj",
    "dependencies": [
      "pixi.js"
    ],
    "title": "Pixi sample",
    "desc": "Simple renderization with [PixiJS](http://www.pixijs.com/), a fast and flexible library to render 2D WebGL content.",
    "img": "pixi.jpeg"
  }
```

We generate:

```js
entry : {
  basic: [
    "pixi.js",
    "PixiBasic.fsproj"
  ]
}
```

"pixi.js" will be include from the node_modules.

I will work on it tomorrow again to not generate the source-map on production mode and see we can mutualise dependencies between the samples to avoid including pixi.js in each bundle.js files.

Edit: Big advantage of this PR, we can update the dependencies in one time just by updating the package.json and regenerating the samples.

### CODE REVIEW

**Comment by alfonsogarciacaro** [comment]
This is a great idea @MangelMaxime! Thank you :clap: :clap:

**Comment by MangelMaxime** [comment]
@whitetigle @alfonsogarciacaro 

If one of you can test this PR and merge it if you agree with the change would be awesome :)

I am more works planned, for the generation of index.html but would be part of the update of the fable docs site. (make them more easier for newcomers, better demo/showcase, etc.)

**Comment by whitetigle** [comment]
Ok so it's working on my side. However, does it mean this: 

```
    <Compile Include="..\Fable.Import.Pixi.fs" />
    <Compile Include="App.fs" />
```

can become: 

```
    <Compile Include="App.fs" />
```

**Comment by MangelMaxime** [comment]
@whitetigle 100% right. I always forget to clean the fsproj after cleaning files has Ionide doesn't complain about it.

**Pull request merged**
