### PR TITLE
Bindings, samples and doc update

### PR DESCRIPTION
**Pull request by whitetigle**
I just shipped a product for one of my client using Fable and pixi. Through this project I have tested and completed and updated  the bindings and most notably the Filters section. Same for animeJS. I have also added some helper modules to smooth the development process. So everything's now here and the samples and doc have been updated consequently.

Could yu please review on you side that everything's working well? When confirmed and merged I'll add the bindings to Fable.Import repo and I think we'll be ready to make some official announcement regarding pixi and animejs.

Thanks!

### CODE REVIEW

**Comment by MangelMaxime** [comment]
Oups... :D

I wanted to push to your master @whitetigle but seems like I push to this repo master. Whatever, I runned `build.sh Build` and tested all the samples with a link on the index.html. They are working :clap: :clap:

**Comment by whitetigle** [comment]
Excellent! Thanks @MangelMaxime 👍

**Comment by alfonsogarciacaro** [comment]
This is awesome, @whitetigle, thanks a lot for everything! :clap: :clap: 💪 🥇

Samples are working without problems for me too 🙆 I have [published them here](http://fable.io/samples-pixi/), but I'll try to make the website a bit nicer :)

Thanks again François!

**Comment by whitetigle** [comment]
My pleasure! 😁 👍 Can't wait to see that Particle Mace sample updated to use pixi 😉

**Pull request merged**
